### PR TITLE
Removes all (now) obsolete features by LSP

### PR DESCRIPTION
**Pull request by rafaeldelboni**
As soon [this](https://github.com/godotengine/godot/pull/35864) is merged in Godot (3.2 and 4.0) it will render many of these plugin functionalities obsolete.

But still, we need syntax highlighting filetype set and some functionalities as snippets. 

NOTE: This PR should be only merged after [this](https://github.com/godotengine/godot/pull/35864) get in the official Godot releases.

### CODE REVIEW

**Comment by Shatur** [comment]
Tested, everything works, thank you!

But when auto-completion popup hides I see the following error message at the buttom: `[coc.nvim] Command:  not found`. I have this message even with the old version. Tested with only coc,nvim and this plugin installed.

**Comment by Rubonnek** [comment]
I suppose this could be merged when 3.2.2 comes around since the TCP patch isn't in 3.2.1 yet.

**Comment by Shatur** [comment]
Yes, need to wait a bit.

**Comment by Rubonnek** [comment]
I've been testing this patch and I'm not able to "go to file" by hovering over "res://path/to/script.gd" and just pressing `gf` to open the file.

**Comment by Rubonnek** [comment]
I found what I was looking for:
https://github.com/clktmr/vim-gdscript3/blob/ebfa25ff879459fb2c3aae9a90b5be40c790c9bf/plugin/gdscript3.vim#L6

**Comment by rawsp33d** [comment]
I wanted to bump this now that 3.2.2 is out and both PRs mentioned in the opening post have been merged.

**Comment by rafaeldelboni** [comment]
I simplified and merged the readme.md

**Comment by Shatur** [comment]
BTW, there is [another Vim plugin](https://github.com/habamax/vim-godot) for Godot with FZF support.

**Comment by clktmr** [comment]
Thanks.  I am currently not working on a Godot project, which is my
response time is quite long..

**Pull request merged**
